# build step 
FROM node:20 AS build  

WORKDIR /app 

COPY package*.json .

RUN npm install  && npm cache clean --force

COPY . . 

RUN npm run build

# deploy step - copy the build folder from the build step to the  folder indicated by nginx settings
FROM nginx:stable-alpine 

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80 

CMD ["nginx","-g", "daemon off;"]