services:
  frontend:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.local-development
    ports: 
       - "80:5173"
    volumes:
      - node_modules:/app/node_modules
      - .:/app
volumes:
  node_modules: {}