services:
  frontend:
    build: 
      context: ../chuck-norris-react
      dockerfile: ./Dockerfile.local-development
    ports: 
       - "80:5173"
    volumes:
      - node_modules:/app/node_modules
      - ../chuck-norris-react:/app
volumes:
  node_modules: {}